### ISSUE TITLE
upgrade openssl - SSL3_GET_SERVER_CERTIFICATE certificate verify failed

### ISSUE THREAD

**Issue by oppianmatt** [docker-library/python#110]
Using `FROM python:2`

installing latest requests from pip and certffi

- requests==2.10.0
- certifi==2016.2.28

```
root@c1cf6ed65b86:/app# python -c 'import ssl; print ssl.OPENSSL_VERSION'#
OpenSSL 1.0.1k 8 Jan 2015
```

```
root@c1cf6ed65b86:/app# python
Python 2.7.11 (default, Mar 9 2016, 02:49:37)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

import requests
requests.get('https://pubsubhubbub.appspot.com/')
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 71, in get
return request('get', url, params=params, kwargs)
File "/usr/local/lib/python2.7/site-packages/requests/api.py", line 57, in request
return session.request(method=method, url=url, kwargs)
File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
resp = self.send(prep, send_kwargs)
File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
r = adapter.send(request, kwargs)
File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 477, in send
raise SSLError(e, request=request)
requests.exceptions.SSLError: ("bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)",)
```

downgrading to `certifi==2015.04.28` works because:

> **Browsers and certificate authorities have concluded that 1024-bit keys are unacceptably weak for certificates, particularly root certificates. For this reason, Mozilla has removed any weak (i.e. 1024-bit key) certificate from its bundle, replacing it with an equivalent strong (i.e. 2048-bit or greater key) certificate from the same CA. Because Mozilla removed these certificates from its bundle, certifi removed them as well.

> Unfortunately, **old versions of OpenSSL (less than 1.0.2)** sometimes fail to validate certificate chains that use the strong roots. For this reason, if you fail to validate a certificate using the certifi.where() mechanism, you can intentionally re-add the 1024-bit roots back into your bundle by calling certifi.old_where() instead. This is not recommended in production: if at all possible you should upgrade to a newer OpenSSL. However, if you have no other option, this may work for you.**

Using `certifi.old_where` is not an acceptable work around since that doesn't fix third party libraries. Best would be to upgrade openssl in the python docker so it works with keys > 1024.

**Comment by oppianmatt** [comment]
More information:

```
root@c37ee196b468:/app# python
Python 2.7.11 (default, May 12 2016, 18:24:08)
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> ssl.OPENSSL_VERSION
'OpenSSL 1.0.1k 8 Jan 2015'
```

**Comment by alex** [comment]
FWIW, Debian stable has OpenSSL 1.0.1t, which I believe has a backport of the fix for this.

**Comment by tianon** [comment]
Indeed!
```console
$ docker run -it --rm python:3 bash
root@fd7bfbaba450:/# pip install requests
Collecting requests
  Downloading requests-2.10.0-py2.py3-none-any.whl (506kB)
    100% |████████████████████████████████| 512kB 2.9MB/s 
Installing collected packages: requests
Successfully installed requests-2.10.0
root@fd7bfbaba450:/# python
Python 3.5.2 (default, Jul  1 2016, 18:28:35) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.get('https://pubsubhubbub.appspot.com/')
<Response [200]>
>>> import ssl
>>> ssl.OPENSSL_VERSION
'OpenSSL 1.0.1t  3 May 2016'
>>> 
```

**Comment by tianon** [comment]
Caveman Python, too:
```console
$ docker run -it --rm python:2 bash
root@8b84a470a01c:/# pip install requests
Collecting requests
  Downloading requests-2.10.0-py2.py3-none-any.whl (506kB)
    100% |████████████████████████████████| 512kB 3.1MB/s 
Installing collected packages: requests
Successfully installed requests-2.10.0
root@8b84a470a01c:/# python
Python 2.7.12 (default, Jul  1 2016, 18:07:47) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.get('https://pubsubhubbub.appspot.com/')
<Response [200]>
>>> import ssl
>>> ssl.OPENSSL_VERSION
'OpenSSL 1.0.1t  3 May 2016'
>>> 
```

**Comment by alex** [comment]
It sounds like this is resolved then.
