### ISSUE TITLE
Need guidance for X11 forwarding

### ISSUE THREAD

**Issue by cywang16** [docker-library/python#237]
Greeting,

I look for a way to do X11 forwarding such as https://hub.docker.com/r/sjawhar/pygame/, where I can display the UI for pygame. I tried setting the environment variable DISPLAY as :1, and map /tmp/.X11-unix folder, but still got this error:
```
root@65a4f83e329d:/setup# python -m pygame.examples.aliens
No protocol specified
No protocol specified
Warning, no sound
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/site-packages/pygame/examples/aliens.py", line 321, in <module>
    if __name__ == '__main__': main()
  File "/usr/local/lib/python3.6/site-packages/pygame/examples/aliens.py", line 188, in main
    bestdepth = pygame.display.mode_ok(SCREENRECT.size, winstyle, 32)
pygame.error: video system not initialized

```
Could you please help? Thanks,

Chun-Yen

**Comment by cywang16** [comment]
Never mind. I made mistake earlier. X11 forward actually works the same way.
