### ISSUE TITLE
Python 2.7.12, urllib2 SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by babaMar** [docker-library/python#255]
```
Python 2.7.12 (default, Dec 16 2016, 03:08:23) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib2                                                                                                                                                                            
>>> req = urllib2.Request('https://hub.docker.com')                                                                                                                                           
>>> urllib2.urlopen(req, None, 10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/urllib2.py", line 155, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 430, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 448, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 408, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 1242, in https_open
    context=self._context)
  File "/usr/local/lib/python2.7/urllib2.py", line 1199, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
```
Something is not right with `ca-bundle` certificates. I also did verify manually passing `/etc/ssl/certs/ca-certificates.crt` and it doesn't work. 
I did manually create `/etc/ssl/certs/ca-bundle.crt` from a `centOS` machine and it magically works (passing it to the `verify=` argument in `requests` though).

**Comment by yosifkit** [comment]
I am unable to reproduce on `python:2.7`, `python:2.7-slim`, or `python:2.7-alpine`.  It looks like your image is fairly old but I pulled a fresh `python:2.7.12` (which is no longer supported) and was still unable to replicate.  Do you perhaps have a corporate proxy that intercepts https traffic and so you need a custom CA cert in the image?

```console
$ docker run -it --rm python:2.7
Python 2.7.14 (default, Jan 10 2018, 06:56:19) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib2
>>> req = urllib2.Request('https://hub.docker.com')
>>> urllib2.urlopen(req, None, 10)
<addinfourl at 139667486616176 whose fp = <socket._fileobject object at 0x7f06e34c5b50>>
>>> 
$ docker run -it --rm python:2.7-slim
Python 2.7.14 (default, Dec 18 2017, 17:44:00) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib2
>>> req = urllib2.Request('https://hub.docker.com')
>>> urllib2.urlopen(req, None, 10)
<addinfourl at 140134609959320 whose fp = <socket._fileobject object at 0x7f73a233e9d0>>
>>> 
$ docker run -it --rm python:2.7-alpine
Python 2.7.14 (default, Jan  9 2018, 21:34:46) 
[GCC 5.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib2
>>> req = urllib2.Request('https://hub.docker.com')
>>> urllib2.urlopen(req, None, 10)
<addinfourl at 140687233532344 whose fp = <socket._fileobject object at 0x7ff44cff89d0>>
>>>
```
```console
$ docker pull python:2.7.12
2.7.12: Pulling from library/python
75a822cd7888: Already exists 
57de64c72267: Already exists 
4306be1e8943: Already exists 
871436ab7225: Already exists 
37c937b0ca47: Pull complete 
03346672e221: Pull complete 
3595e3d63695: Pull complete 
Digest: sha256:4f5e0adc60fda1c34c6a2759a44942c62bc6e930b91787a688a44f81d342fef0
Status: Downloaded newer image for python:2.7.12
$ docker run -it --rm python:2.7.12
Python 2.7.12 (default, Dec 16 2016, 03:08:23) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib2
>>> req = urllib2.Request('https://hub.docker.com')
>>> urllib2.urlopen(req, None, 10)
<addinfourl at 139919264504432 whose fp = <socket._fileobject object at 0x7f41826d9bd0>>
>>> 

```

**Comment by babaMar** [comment]
Checked that, it's as you say, thanks a lot for looking into it, it helped me a lot.
