### ISSUE TITLE
AssertionError raised when installing pip 18.1

### ISSUE THREAD

**Issue by lieyanqzu** [docker-library/python#368]
when installing pip 18.1 via `get-pip.py`, AssertionError was raised.
It seems like `get-pip.py` now use pip 19.0 to install pip itself, and pip 19.0 don't support `--no-cache-dir` option for installing wheel anymore.
https://github.com/pypa/pip/blob/master/src/pip/_internal/wheel.py#L843

Error message:
```
Collecting wheel
  Downloading https://files.pythonhosted.org/packages/ff/47/1dfa4795e24fd6f93d5d58602dd716c3f101cfd5a77cd9acbe519b44a0a9/wheel-0.32.3-py2.py3-none-any.whl
Exception:
Traceback (most recent call last):
  File "/tmp/tmp2rvdkg6l/pip.zip/pip/_internal/cli/base_command.py", line 176, in main
    status = self.run(options, args)
  File "/tmp/tmp2rvdkg6l/pip.zip/pip/_internal/commands/install.py", line 346, in run
    session=session, autobuilding=True
  File "/tmp/tmp2rvdkg6l/pip.zip/pip/_internal/wheel.py", line 848, in build
    assert building_is_possible
AssertionError
```

**Comment by lieyanqzu** [comment]
Well, pip 19.0.1 updated 😆 and this issue can be closed.
