### ISSUE TITLE
File descriptors are not worked with Python 3.8 images

### ISSUE THREAD

**Issue by Surgo** [docker-library/python#453]
'`OSError: [Errno 88] Socket operation on non-socket`' error occurred on Python 3.8 images. Python 3.7 images are works fine.

* Image: `python:3.8-slim-buster`

    ```console
    $ docker run -it python:3.8-slim-buster
    Python 3.8.1 (default, Feb  2 2020, 08:49:34)
    [GCC 8.3.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import socket
    >>> socket.fromfd(0, socket.AF_UNIX, socket.SOCK_STREAM)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python3.8/socket.py", line 544, in fromfd
        return socket(family, type, proto, nfd)
      File "/usr/local/lib/python3.8/socket.py", line 231, in __init__
        _socket.socket.__init__(self, family, type, proto, fileno)
    OSError: [Errno 88] Socket operation on non-socket
    >>>
    ```

* Image: `python:3.8-alpine3.11`

    ```console
    $ docker run -it python:3.8-alpine3.11
    Python 3.8.1 (default, Jan 18 2020, 02:42:17)
    [GCC 9.2.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import socket
    >>> socket.fromfd(0, socket.AF_UNIX, socket.SOCK_STREAM)
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/usr/local/lib/python3.8/socket.py", line 544, in fromfd
        return socket(family, type, proto, nfd)
      File "/usr/local/lib/python3.8/socket.py", line 231, in __init__
        _socket.socket.__init__(self, family, type, proto, fileno)
    OSError: [Errno 88] Not a socket
    ```

* Image: `python:3.7.6-slim-buster`

    ```console
    $ docker run -it python:3.7.6-slim-buster
    Python 3.7.6 (default, Feb  2 2020, 09:11:24)
    [GCC 8.3.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import socket
    >>> socket.fromfd(0, socket.AF_UNIX, socket.SOCK_STREAM)
    <socket.socket fd=3, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0>
    ```

**Comment by Surgo** [comment]
Oh... It's cpython's 🐛  https://bugs.python.org/issue39685

**Comment by wglambert** [comment]
Since this issue is only on 3.8 and affects all variants I would think this a bug/change upstream

Maybe looking through the commits of `socket.py` might yield something https://github.com/python/cpython/commits/3.8/Lib/socket.py
Python 3.7 was release June 27, 2018 so maybe sometime between then and 3.8's release October 14th, 2019

**Comment by Surgo** [comment]
```
kosei:pikachu:  40 minutes ago
https://bugs.python.org/issue39685
もしかしたらこの cpython のバグかもしれないです :thinking_face:
kosei:pikachu:  36 minutes ago
リンクされている issue に
https://bugs.python.org/issue35415
この変更以降出るようになったと書いてありますね・・・
https://github.com/python/cpython/commit/e991270363435da12049ecfe70bb69bd9c14b535
やっぱり私の技術力ではお手上げだ
atsuoishimoto  33 minutes ago
なるほど。。。
```

**Comment by Surgo** [comment]
@wglambert Thank you for your advice :)
