### ISSUE TITLE
Name resolution fails out of the box on python:windowsservercore-ltsc2016

### ISSUE THREAD

**Issue by bsolomon1124** [docker-library/python#459]
[please let me know if this is better-suited to be filed upstream]

```shell
docker pull python:windowsservercore-ltsc2016
docker container run -it --rm ^
    --entrypoint="C:\\Windows\\system32\\cmd.exe" ^
    python:windowsservercore-ltsc2016
```

Installing from PyPI does not work:

```
C:\>py -3 -m pip install --upgrade six
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000002D4155E6A00>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/six/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000002D4155D59A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/six/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000002D4155D5B50>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/six/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000002D4155D5BE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/six/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x000002D4155D5AC0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/six/
ERROR: Could not find a version that satisfies the requirement six (from versions: none)
ERROR: No matching distribution found for six
```

Which, in turn, seems to be a `getaddrinfo()` failure:

```
C:\>py -3
Python 3.8.2 (tags/v3.8.2:7b3ab59, Feb 25 2020, 23:03:10) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> socket.getaddrinfo('pypi.org', 443)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed
>>> socket.getaddrinfo('pypi.org', 80)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\lib\socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed
```

Do there need to be any additional steps taken for DNS resolution?

```
C:\Users\brsolomon>docker info
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.3.1-tp-docker)
  mutagen: Synchronize files with Docker Desktop (Docker Inc., testing)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 19.03.5
 Storage Driver: windowsfilter (windows) lcow (linux)
  Windows:
  LCOW:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 17763 (17763.1.amd64fre.rs5_release.180914-1434)
 Operating System: Windows 10 Enterprise Version 1809 (OS Build 17763.1098)
 OSType: windows
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.85GiB
 Name: USARRBRSOLOMON0
 ID: NZ7E:DCR7:M43E:YLJF:TPHN:RSHM:W2SV:DYI2:BXRL:AHNU:XSUE:PMMW
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: true
  File Descriptors: -1
  Goroutines: 28
  System Time: 2020-03-25T10:19:47.0744811-04:00
  EventsListeners: 1
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by bsolomon1124** [comment]
Related issue: https://github.com/pypa/pip/issues/7460#issuecomment-564368010

```
C:\Users\brsolomon>docker container run -it --rm ^
More?     --entrypoint="C:\\Windows\\system32\\cmd.exe" ^
More?     python:windowsservercore-ltsc2016
Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\>nslookup pypi.org
DNS request timed out.
    timeout was 2 seconds.
Server:  UnKnown
Address:  172.21.208.1

DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
DNS request timed out.
    timeout was 2 seconds.
*** Request to UnKnown timed-out
```

**Comment by tianon** [comment]
I'm not able to reproduce: :confused:

```console
$ docker pull python:windowsservercore-ltsc2016
windowsservercore-ltsc2016: Pulling from library/python
Digest: sha256:d871b7ef1faffd5448637956741b71153fe2c742941e6f60fd00ab2ea002f957
Status: Image is up to date for python:windowsservercore-ltsc2016

$ docker run --rm python:windowsservercore-ltsc2016 python -c "import socket; print(socket.getaddrinfo('pypi.org', 443))"
[(<AddressFamily.AF_INET: 2>, 0, 0, '', ('151.101.0.223', 443)), (<AddressFamily.AF_INET: 2>, 0, 0, '', ('151.101.128.223', 443)), (<AddressFamily.AF_INET: 2>, 0, 0, '', ('151.101.192.223', 443)), (<AddressFamily.AF_INET: 2>, 0, 0, '', ('151.101.64.223', 443))]
```

In my experience however, Windows container networking is a bit fickle sometimes. :disappointed:

**Comment by bsolomon1124** [comment]
@tianon OK, thanks for that regardless. I'll close this but comment here if I find some particular change that needs made, even if it is not for all cases.

**Comment by bsolomon1124** [comment]
Oddly enough: connecting to a VPN first solved this problem.  Not going to hurt my brain thinking too hard about why that might be (maybe because it changes the default resolver from localhost to something else, where localhost works on the host but not container), but I know I've seen this mentioned on a docker-for-win issue as well.
