### ISSUE TITLE
pip install failed using http proxy

### ISSUE THREAD

**Issue by kzhui125** [docker-library/python#464]
Dockerfile:

```
FROM python:3.6.3
COPY . /app
WORKDIR /app
RUN pip install --no-cache-dir flask
ENTRYPOINT ["python"]
CMD ["app.py"]
```

docker build --build-arg HTTP_PROXY="http://192.168.1.10:1080" --build-arg HTTPS_PROXY="http://192.168.1.10:1080" -t flask-sample:latest

```
Sending build context to Docker daemon  4.096kB
Step 1/6 : FROM python:3.6.3
 ---> a8f7167de312
Step 2/6 : COPY . /app
 ---> 600e50e4058b
Step 3/6 : WORKDIR /app
 ---> Running in 12bb12b4d9bc
Removing intermediate container 12bb12b4d9bc
 ---> 8b8cf38db809
Step 4/6 : RUN pip install --no-cache-dir flask
 ---> Running in 3b5147d6ca01
Collecting flask
  Could not fetch URL https://pypi.python.org/simple/flask/: There was a problem confirming the ssl certificate: EOF occurred in violation of protocol (_ssl.c:777) - skipping
  Could not find a version that satisfies the requirement flask (from versions: )
No matching distribution found for flask
The command '/bin/sh -c pip install --no-cache-dir flask' returned a non-zero code: 1
```

**Comment by kzhui125** [comment]
sometimes this error:
```
Collecting flask
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 589, in urlopen
    self._prepare_proxy(conn)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 797, in _prepare_proxy
    conn.connect()
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/connection.py", line 289, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py", line 308, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.6/ssl.py", line 407, in wrap_socket
    _context=self, _session=session)
  File "/usr/local/lib/python3.6/ssl.py", line 814, in __init__
    self.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 1068, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:777)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/packages/urllib3/connectionpool.py", line 621, in urlopen
    raise SSLError(e)
pip._vendor.requests.packages.urllib3.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:777)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/usr/local/lib/python3.6/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/local/lib/python3.6/site-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/usr/local/lib/python3.6/site-packages/pip/download.py", line 659, in unpack_http_url
    hashes)
  File "/usr/local/lib/python3.6/site-packages/pip/download.py", line 853, in _download_http_url
    stream=True,
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 488, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/local/lib/python3.6/site-packages/pip/_vendor/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
pip._vendor.requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:777)
```

**Comment by kzhui125** [comment]
```
FROM python:3.6.3
COPY . /app
WORKDIR /app
RUN pwd
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
RUN python get-pip.py
RUN pip install flask
ENTRYPOINT ["python"]
CMD ["app.py"]
```

now it works
