### ISSUE TITLE
Curses is missing

### ISSUE THREAD

**Issue by crepererum** [docker-library/python#51]
The `/usr/local/lib/python2.7/lib-dynload/_curses.so` is missing on the `python:2.7-slim` image which disables the usage of the builtin `curses` module.

**Comment by tianon** [comment]
Arg!  I can reproduce:
```console
$ docker run -it --rm python:2-slim
Python 2.7.10 (default, Jun  3 2015, 00:44:20) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import curses
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/curses/__init__.py", line 15, in <module>
    from _curses import *
ImportError: No module named _curses
```
