### ISSUE TITLE
python:3.8-slim has apparently completely broken pip/pipenv

### ISSUE THREAD

**Issue by JohnPeacockMessageSystems** [docker-library/python#516]
Just since 09/10, images built from python:3.8-slim are mysteriously breaking when I try and install pipenv as part of a github actions pipeline:
```
Creating a virtualenv for this project…
Pipfile: /github/workspace/***/tests/Pipfile
Using /usr/local/bin/python3.8 (3.8.5) to create virtualenv…
RuntimeError: failed to build image setuptools, pip, wheel because:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 58, in _install
    if not installer.has_image():
  File "/usr/local/lib/python3.8/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 143, in has_image
    return self._image_dir.exists() and next(self._image_dir.iterdir()) is not None
StopIteration

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 60, in _install
    installer.install(creator.interpreter.version_info)
  File "/usr/local/lib/python3.8/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 46, in install
    for name, module in self._console_scripts.items():
  File "/usr/local/lib/python3.8/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 116, in _console_scripts
    entry_points = self._dist_info / "entry_points.txt"
  File "/usr/local/lib/python3.8/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 103, in _dist_info
    raise RuntimeError(msg)  # pragma: no cover
RuntimeError: no .dist-info at /github/home/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/pip-20.2.2-py2.py3-none-any, has pip

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/virtualenv/seed/embed/via_app_data/via_app_data.py", line 60, in _install
    installer.install(creator.interpreter.version_info)
  File "/usr/local/lib/python3.8/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 46, in install
    for name, module in self._console_scripts.items():
  File "/usr/local/lib/python3.8/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 116, in _console_scripts
    entry_points = self._dist_info / "entry_points.txt"
  File "/usr/local/lib/python3.8/site-packages/virtualenv/seed/embed/via_app_data/pip_install/base.py", line 103, in _dist_info
    raise RuntimeError(msg)  # pragma: no cover
RuntimeError: no .dist-info at /github/home/.local/share/virtualenv/wheel/3.8/image/1/CopyPipInstall/wheel-0.35.1-py2.py3-none-any, has wheel
```

**Comment by wglambert** [comment]
Is it only reproducible on github actions? Installing pipenv through a Dockerfile normally seems to work fine for me

```console
$ docker build -t python:test - << EOF
> FROM python:3.8-slim
> RUN pip install pipenv
> EOF
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM python:3.8-slim
3.8-slim: Pulling from library/python
d121f8d1c412: Pull complete 
ca572574cc82: Pull complete 
776716b0aa87: Pull complete 
c37461631ba3: Pull complete 
bdb458dd27ea: Pull complete 
Digest: sha256:52918deb46db660b7d4531441d86ecc250cb23c3b5c97949c2de016b12f78028
Status: Downloaded newer image for python:3.8-slim
 ---> 6cf621cb1327
Step 2/2 : RUN pip install pipenv
 ---> Running in 4025164eda58
Collecting pipenv
  Downloading pipenv-2020.8.13-py2.py3-none-any.whl (3.9 MB)
Collecting virtualenv-clone>=0.2.5
  Downloading virtualenv_clone-0.5.4-py2.py3-none-any.whl (6.6 kB)
Collecting certifi
  Downloading certifi-2020.6.20-py2.py3-none-any.whl (156 kB)
Requirement already satisfied: pip>=18.0 in /usr/local/lib/python3.8/site-packages (from pipenv) (20.2.3)
Collecting virtualenv
  Downloading virtualenv-20.0.31-py2.py3-none-any.whl (4.9 MB)
Requirement already satisfied: setuptools>=36.2.1 in /usr/local/lib/python3.8/site-packages (from pipenv) (50.3.0)
Collecting filelock<4,>=3.0.0
  Downloading filelock-3.0.12-py3-none-any.whl (7.6 kB)
Collecting distlib<1,>=0.3.1
  Downloading distlib-0.3.1-py2.py3-none-any.whl (335 kB)
Collecting six<2,>=1.9.0
  Downloading six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting appdirs<2,>=1.4.3
  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Installing collected packages: virtualenv-clone, certifi, filelock, distlib, six, appdirs, virtualenv, pipenv
Successfully installed appdirs-1.4.4 certifi-2020.6.20 distlib-0.3.1 filelock-3.0.12 pipenv-2020.8.13 six-1.15.0 virtualenv-20.0.31 virtualenv-clone-0.5.4
Removing intermediate container 4025164eda58
 ---> ddcef97fd98c
Successfully built ddcef97fd98c
Successfully tagged python:test

$ docker run -it --rm python:test bash
root@98fb0ba890a0:/# pipenv shell
Creating a virtualenv for this project…
Pipfile: //Pipfile
Using /usr/local/bin/python3 (3.8.5) to create virtualenv…
⠸ Creating virtual environment...created virtual environment CPython3.8.5.final.0-64 in 866ms
  creator CPython3Posix(dest=/root/.local/share/virtualenvs/-DfY8dI1n, clear=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
    added seed packages: pip==20.2.2, setuptools==49.6.0, wheel==0.35.1
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

✔ Successfully created virtual environment! 
Virtualenv location: /root/.local/share/virtualenvs/-DfY8dI1n
Creating a Pipfile for this project…
Launching subshell in virtual environment…
root@98fb0ba890a0:/#  . /root/.local/share/virtualenvs/-DfY8dI1n/bin/activate
() root@98fb0ba890a0:/#
```

**Comment by JohnPeacockMessageSystems** [comment]
It appears to be a combination of things all working together to make it very hard to recognize. The .local/share folders are mapped from the underlying instance and apparently something in there is causing problems. I can get a good clean build *once* and only once; if I delete the contents of .local/share then it works again.

One additional complication is that the github runner is executing as a non-root user. I'm still trying to recreate a simplified environment to trigger it, but one that is interesting to me is that within the pipenv shell, The installed pip is 20.2.2 but outside of the shell it's 20.2.3 (which only got added to the python images in the last day or so).

I'll keep trying to create a reproduction recipe outside of the git runner environment (which we have local so I have more control over it than it it was on Github hardware).

**Comment by JohnPeacockMessageSystems** [comment]
After a lot of swearing and a blood sacrifice to the gods, I've determined that the global cleanup for github actions is deleting the **files** under .local/share/virtualenv but not the **directories**, which breaks pip/wheel something awful with a really misleading error message. the Runner code shipped a new release Sept 11 as well, so that's why it looked like the Python image bump was to blame.
