### ISSUE TITLE
Pip broken on python:2-windowsservercore container image

### ISSUE THREAD

**Issue by dlangesh** [docker-library/python#583]
I have pulled python:2-windowsservercore & created a container.
python working fine, however pip is throwing error as given below

No changes made to image and no additional tool installed( its base image from github)

```cmd
**C:\>pip**
Traceback (most recent call last):
  File "c:\python\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python\Scripts\pip.exe\__main__.py", line 4, in <module>
  File "c:\python\lib\site-packages\pip\_internal\cli\main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "c:\python\lib\site-packages\pip\_internal\cli\autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "c:\python\lib\site-packages\pip\_internal\cli\main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "c:\python\lib\site-packages\pip\_internal\cli\cmdoptions.py", line 31, in <module>
    from pip._internal.utils.ui import BAR_TYPES
  File "c:\python\lib\site-packages\pip\_internal\utils\ui.py", line 64, in <module>
    _BaseBar = _select_progress_class(IncrementalBar, Bar)  # type: Any
  File "c:\python\lib\site-packages\pip\_internal\utils\ui.py", line 57, in _select_progress_class
    six.text_type().join(characters).encode(encoding)
LookupError: unknown encoding: cp0

**C:\>python -m pip install -U pip**
Traceback (most recent call last):
  File "C:\Python\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Python\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python\lib\site-packages\pip\__main__.py", line 16, in <module>
    from pip._internal.cli.main import main as _main  # isort:skip # noqa
  File "C:\Python\lib\site-packages\pip\_internal\cli\main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "C:\Python\lib\site-packages\pip\_internal\cli\autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "C:\Python\lib\site-packages\pip\_internal\cli\main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "C:\Python\lib\site-packages\pip\_internal\cli\cmdoptions.py", line 31, in <module>
    from pip._internal.utils.ui import BAR_TYPES
  File "C:\Python\lib\site-packages\pip\_internal\utils\ui.py", line 64, in <module>
    _BaseBar = _select_progress_class(IncrementalBar, Bar)  # type: Any
  File "C:\Python\lib\site-packages\pip\_internal\utils\ui.py", line 57, in _select_progress_class
    six.text_type().join(characters).encode(encoding)
LookupError: unknown encoding: cp0
```

**Comment by tianon** [comment]
I'm able to reproduce, but the encoding in my error message is `cp65001`, not `cp0`: :confused:

```console
$ docker pull python:2-windowsservercore
2-windowsservercore: Pulling from library/python
Digest: sha256:2bedbd91529fa5e98354dd53d8f5bec79aba9646e6b25ff25e9b4639a7d5d2f6
Status: Image is up to date for python:2-windowsservercore
docker.io/library/python:2-windowsservercore

$ docker run -it --rm python:2-windowsservercore powershell

Windows PowerShell 
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\> pip --version
Traceback (most recent call last):
  File "c:\python\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python\Scripts\pip.exe\__main__.py", line 4, in <module>
  File "c:\python\lib\site-packages\pip\_internal\cli\main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "c:\python\lib\site-packages\pip\_internal\cli\autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "c:\python\lib\site-packages\pip\_internal\cli\main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "c:\python\lib\site-packages\pip\_internal\cli\cmdoptions.py", line 31, in <module>
    from pip._internal.utils.ui import BAR_TYPES
  File "c:\python\lib\site-packages\pip\_internal\utils\ui.py", line 64, in <module>
    _BaseBar = _select_progress_class(IncrementalBar, Bar)  # type: Any
  File "c:\python\lib\site-packages\pip\_internal\utils\ui.py", line 57, in _select_progress_class
    six.text_type().join(characters).encode(encoding)
LookupError: unknown encoding: cp65001
```

**Comment by tianon** [comment]
Ah, if I set `PYTHONIOENCODING` to `UTF-8`, it works.

However, Python 2 is unfortunately EOL, so this isn't something we'll be fixing in the published images (which are not going to be updated for any reason).

That being said, you might be interested in https://github.com/docker-library/pypy/pull/54.

**Comment by dlangesh** [comment]
set PYTHONIOENCODING to UTF-8 is working

do pypy support window image? i was looking for windows image python 2

**Comment by yosifkit** [comment]
We are working to add `pypy` windows images and `pypy` upstream still supports a python 2 interpreter.
