### ISSUE TITLE
Broken package installation with latest changes on image

### ISSUE THREAD

**Issue by CrisBMoya** [docker-library/python#616]
Hello.

I recently stumbled into a problem while trying to install "pyrle" on the most recent image of python (as of 2021-05-14).

If you try to build a docker container as follows (by using `docker build .`):
```
FROM python:3.8

RUN pip install -U pip
RUN pip install --upgrade Cython
RUN pip install pyrle==0.0.31
```

The problem comes at the last line `RUN pip install pyrle==0.0.31`:

```
#10 3.461 Collecting pyrle==0.0.31
#10 3.477   Downloading pyrle-0.0.31.tar.gz (346 kB)
#10 5.358     ERROR: Command errored out with exit status 1:
#10 5.358      command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-q8rn7soo/pyrle_d8db1eea418b4360a4f1ee10d4ce804f/setup.py'"'"'; __file__='"'"'/tmp/pip-install-q8rn7soo/pyrle_d8db1eea418b4360a4f1ee10d4ce804f/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-x1xlg8qh
#10 5.358          cwd: /tmp/pip-install-q8rn7soo/pyrle_d8db1eea418b4360a4f1ee10d4ce804f/
#10 5.358     Complete output (28 lines):
#10 5.358     Compiling pyrle/src/rle.pyx because it depends on /usr/local/lib/python3.8/site-packages/Cython/Includes/libc/math.pxd.
#10 5.358     Compiling pyrle/src/coverage.pyx because it depends on /usr/local/lib/python3.8/site-packages/Cython/Includes/libc/math.pxd.
#10 5.358     [1/2] Cythonizing pyrle/src/coverage.pyx
#10 5.358     [2/2] Cythonizing pyrle/src/rle.pyx
#10 5.358     running egg_info
#10 5.358     creating /tmp/pip-pip-egg-info-x1xlg8qh/pyrle.egg-info
#10 5.358     writing /tmp/pip-pip-egg-info-x1xlg8qh/pyrle.egg-info/PKG-INFO
#10 5.358     Traceback (most recent call last):
#10 5.358       File "<string>", line 1, in <module>
#10 5.358       File "/tmp/pip-install-q8rn7soo/pyrle_d8db1eea418b4360a4f1ee10d4ce804f/setup.py", line 29, in <module>
#10 5.358         setup(name='pyrle',
#10 5.358       File "/usr/local/lib/python3.8/distutils/core.py", line 148, in setup
#10 5.358         dist.run_commands()
#10 5.358       File "/usr/local/lib/python3.8/distutils/dist.py", line 966, in run_commands
#10 5.358         self.run_command(cmd)
#10 5.358       File "/usr/local/lib/python3.8/distutils/dist.py", line 985, in run_command
#10 5.358         cmd_obj.run()
#10 5.358       File "/usr/local/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 292, in run
#10 5.358         writer(self, ep.name, os.path.join(self.egg_info, ep.name))
#10 5.358       File "/usr/local/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 628, in write_pkg_info
#10 5.358         metadata.write_pkg_info(cmd.egg_info)
#10 5.358       File "/usr/local/lib/python3.8/distutils/dist.py", line 1117, in write_pkg_info
#10 5.358         self.write_pkg_file(pkg_info)
#10 5.358       File "/usr/local/lib/python3.8/site-packages/setuptools/dist.py", line 172, in write_pkg_file
#10 5.358         license = rfc822_escape(self.get_license())
#10 5.358       File "/usr/local/lib/python3.8/distutils/util.py", line 475, in rfc822_escape
#10 5.358         lines = header.split('\n')
#10 5.358     AttributeError: 'list' object has no attribute 'split'
#10 5.358     ----------------------------------------
#10 5.358 WARNING: Discarding https://files.pythonhosted.org/packages/9a/5f/6efabd8509cb3c2041e86a4b0b483d3805b6055480c8b19bae053a2edcee/pyrle-0.0.31.tar.gz#sha256=60c7385ac809854b1d024b7006e4fecd0ca7c9f5290367f963cbc08d458abe4c (from https://pypi.org/simple/pyrle/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
#10 5.359 ERROR: Could not find a version that satisfies the requirement pyrle==0.0.31 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.0.19, 0.0.21, 0.0.22, 0.0.23, 0.0.24, 0.0.25, 0.0.26, 0.0.27, 0.0.28, 0.0.29, 0.0.30, 0.0.31, 0.0.32)
#10 5.359 ERROR: No matching distribution found for pyrle==0.0.31
------
executor failed running [/bin/sh -c pip install --no-cache-dir -r requirements.txt]: exit code: 1

```

If I try to install pyrle with Ubuntu backend, it works fine. It also works fine under Windows. It works fine for other pyrle versions too (the latest, some older, same with Cython).

So, for example:
```
FROM ubuntu

RUN apt -y update
RUN apt -y upgrade
RUN apt install -y python3-pip

RUN pip install -U pip
RUN pip install --upgrade Cython
RUN pip install pyrle==0.0.31
```

Works perfectly fine.

It also works fine by using older images like `FROM python:3.8.9` which was updated 11 days ago (around 2021-05-03). The problem exist within all new images (python:latest, alpine, slim, etc), updated on 2021-05-12.

**Comment by wglambert** [comment]
Yeah that's weird... In the meantime you can use the version right before the last update `python@sha256:374f9659026b1c4279ad6f1752dee8ec01c6a59516a20695c13251aafa8b35a5`
https://github.com/docker-library/repo-info/blob/200b2f7868c471c2eb068252e9ed73d951d8b226/repos/python/remote/3.8-buster.md

It builds successfully:

<details>
<summary> docker build </summary>

```console
$ docker build -t python:test - << EOF
FROM python@sha256:374f9659026b1c4279ad6f1752dee8ec01c6a59516a20695c13251aafa8b35a5

RUN pip install -U pip
RUN pip install --upgrade Cython
RUN pip install pyrle==0.0.31
EOF
Sending build context to Docker daemon  2.048kB
Step 1/4 : FROM python@sha256:374f9659026b1c4279ad6f1752dee8ec01c6a59516a20695c13251aafa8b35a5
docker.io/library/python@sha256:374f9659026b1c4279ad6f1752dee8ec01c6a59516a20695c13251aafa8b35a5: Pulling from library/python
bd8f6a7501cc: Pull complete 
44718e6d535d: Pull complete 
efe9738af0cb: Pull complete 
f37aabde37b8: Pull complete 
3923d444ed05: Pull complete 
1ecef690e281: Pull complete 
7398f7b5a4db: Pull complete 
4bc12dba33a6: Pull complete 
21b6e61460b3: Pull complete 
Digest: sha256:374f9659026b1c4279ad6f1752dee8ec01c6a59516a20695c13251aafa8b35a5
Status: Downloaded newer image for python@sha256:374f9659026b1c4279ad6f1752dee8ec01c6a59516a20695c13251aafa8b35a5
 ---> 2645783ebe44
Step 2/4 : RUN pip install -U pip
 ---> Running in 4b13d7349a47
Requirement already satisfied: pip in /usr/local/lib/python3.8/site-packages (21.1.1)
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv
Removing intermediate container 4b13d7349a47
 ---> c903f4fde377
Step 3/4 : RUN pip install --upgrade Cython
 ---> Running in 91ec4ebd7b85
Collecting Cython
  Downloading Cython-0.29.23-cp38-cp38-manylinux1_x86_64.whl (1.9 MB)
Installing collected packages: Cython
Successfully installed Cython-0.29.23
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv
Removing intermediate container 91ec4ebd7b85
 ---> 9d6f1d21c85f
Step 4/4 : RUN pip install pyrle==0.0.31
 ---> Running in f2553d93339f
Collecting pyrle==0.0.31
  Downloading pyrle-0.0.31.tar.gz (346 kB)
Requirement already satisfied: cython in /usr/local/lib/python3.8/site-packages (from pyrle==0.0.31) (0.29.23)
Collecting pandas
  Downloading pandas-1.2.4-cp38-cp38-manylinux1_x86_64.whl (9.7 MB)
Collecting tabulate
  Downloading tabulate-0.8.9-py3-none-any.whl (25 kB)
Collecting numpy
  Downloading numpy-1.20.3-cp38-cp38-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (15.4 MB)
Collecting natsort
  Downloading natsort-7.1.1-py3-none-any.whl (35 kB)
Collecting python-dateutil>=2.7.3
  Downloading python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pytz>=2017.3
  Downloading pytz-2021.1-py2.py3-none-any.whl (510 kB)
Collecting six>=1.5
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: pyrle
  Building wheel for pyrle (setup.py): started
  Building wheel for pyrle (setup.py): finished with status 'done'
  Created wheel for pyrle: filename=pyrle-0.0.31-cp38-cp38-linux_x86_64.whl size=1644955 sha256=fa19d01327853d3a6e28c0c7bc24588c616235e6e7292324d42105eae504874a
  Stored in directory: /root/.cache/pip/wheels/6e/37/cd/472970609d7c731d46e8ad52161488e82412ed99d06dbf9bfc
Successfully built pyrle
Installing collected packages: six, pytz, python-dateutil, numpy, tabulate, pandas, natsort, pyrle
Successfully installed natsort-7.1.1 numpy-1.20.3 pandas-1.2.4 pyrle-0.0.31 python-dateutil-2.8.1 pytz-2021.1 six-1.16.0 tabulate-0.8.9
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv
Removing intermediate container f2553d93339f
 ---> 7f743f93a2ab
Successfully built 7f743f93a2ab
Successfully tagged python:test
```

</details>

**Comment by wanjuntham** [comment]
Same happened to me for `python:3.9-alpine` since morning 9AM GMT+8 today.
I tried to install `grpcio` which is specified in my `requirements.txt`, but it is failing at that step.
It didnt happen for `python:3.9-buster`, only most of the alpine images it seems.

docker build logs
```
PS C:\> docker image build -t testtest .
[+] Building 7.4s (8/9)
 => [internal] load build definition from Dockerfile                                                                                                                                                                                                                                                  0.0s 
 => => transferring dockerfile: 32B                                                                                                                                                                                                                                                                   0.0s 
 => [internal] load .dockerignore                                                                                                                                                                                                                                                                     0.0s 
 => => transferring context: 34B                                                                                                                                                                                                                                                                      0.0s 
 => [internal] load metadata for docker.io/library/python:3.9-alpine                                                                                                                                                                                                                                  1.1s 
 => [1/5] FROM docker.io/library/python:3.9-alpine@sha256:853365cd7245aec1580879933f2c5ea1a45c1ceb868c05480a58cba443ffb1e5                                                                                                                                                                            0.0s 
 => [internal] load build context                                                                                                                                                                                                                                                                     0.0s 
 => => transferring context: 125B                                                                                                                                                                                                                                                                     0.0s 
 => CACHED [2/5] WORKDIR /app                                                                                                                                                                                                                                                                         0.0s 
 => CACHED [3/5] COPY requirements.txt requirements.txt                                                                                                                                                                                                                                               0.0s 
 => ERROR [4/5] RUN python -m pip install -r requirements.txt                                                                                                                                                                                                                                         6.2s 
------
 > [4/5] RUN python -m pip install -r requirements.txt:
#8 2.242 Collecting grpcio==1.39.0
#8 2.304   Downloading grpcio-1.39.0.tar.gz (21.3 MB)
#8 5.910     ERROR: Command errored out with exit status 1:
#8 5.910      command: /usr/local/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-t53sk6jr/grpcio_a2d90adc552c43d7a81048d9518ea9bc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-t53sk6jr/grpcio_a2d90adc552c43d7a81048d9518ea9bc/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-cn2t5__p    
#8 5.910          cwd: /tmp/pip-install-t53sk6jr/grpcio_a2d90adc552c43d7a81048d9518ea9bc/
#8 5.910     Complete output (11 lines):
#8 5.910     Traceback (most recent call last):
#8 5.910       File "<string>", line 1, in <module>
#8 5.910       File "/tmp/pip-install-t53sk6jr/grpcio_a2d90adc552c43d7a81048d9518ea9bc/setup.py", line 257, in <module>
#8 5.910         if check_linker_need_libatomic():
#8 5.910       File "/tmp/pip-install-t53sk6jr/grpcio_a2d90adc552c43d7a81048d9518ea9bc/setup.py", line 204, in check_linker_need_libatomic
#8 5.910         cpp_test = subprocess.Popen([cxx, '-x', 'c++', '-std=c++11', '-'],
#8 5.910       File "/usr/local/lib/python3.9/subprocess.py", line 951, in __init__
#8 5.910         self._execute_child(args, executable, preexec_fn, close_fds,
#8 5.910       File "/usr/local/lib/python3.9/subprocess.py", line 1821, in _execute_child
#8 5.910         raise child_exception_type(errno_num, err_msg, err_filename)
#8 5.910     FileNotFoundError: [Errno 2] No such file or directory: 'c++'
#8 5.910     ----------------------------------------
#8 5.910 WARNING: Discarding https://files.pythonhosted.org/packages/07/ea/398472e896f529d23fb58e33f01298dfc554a341d58f87c1ea5ad817208e/grpcio-1.39.0.tar.gz#sha256=57974361a459d6fe04c9ae0af1845974606612249f467bbd2062d963cb90f407 (from https://pypi.org/simple/grpcio/). Command errored out with exit 
status 1: python setup.py egg_info Check the logs for full command output.
#8 5.911 ERROR: Could not find a version that satisfies the requirement grpcio==1.39.0 (from versions: 0.4.0a0, 0.4.0a1, 0.4.0a2, 0.4.0a3, 0.4.0a4, 0.4.0a5, 0.4.0a6, 0.4.0a7, 0.4.0a8, 0.4.0a13, 0.4.0a14, 0.5.0a0, 0.5.0a1, 0.5.0a2, 0.9.0a0, 0.9.0a1, 0.10.0a0, 0.11.0b0, 0.11.0b1, 0.12.0b0, 0.13.0, 0.13.1rc1, 0.13.1, 0.14.0rc1, 0.14.0, 0.15.0, 1.0.0rc1, 1.0.0rc2, 1.0.0, 1.0.1rc1, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.3, 1.2.0, 1.2.1, 1.3.0, 1.3.5, 1.4.0, 1.6.0, 1.6.3, 1.7.0, 1.7.3, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.6, 1.9.0rc1, 1.9.0rc2, 1.9.0rc3, 1.9.0, 1.9.1, 1.10.0rc1, 1.10.0rc2, 1.10.0, 1.10.1rc1, 1.10.1rc2, 1.10.1, 1.11.0rc1, 1.11.0rc2, 1.11.0, 1.11.1rc1, 1.11.1, 1.12.0rc1, 1.12.0, 1.12.1, 1.13.0rc1, 1.13.0rc2, 1.13.0rc3, 1.13.0, 1.14.0rc1, 1.14.0rc2, 1.14.0, 1.14.1, 1.14.2rc1, 1.14.2, 1.15.0rc1, 1.15.0, 1.16.0rc1, 1.16.0, 1.16.1rc1, 1.16.1, 1.17.0rc1, 1.17.0, 1.17.1rc1, 1.17.1, 1.18.0rc1, 1.18.0, 1.19.0rc1, 1.19.0, 1.20.0rc1, 1.20.0rc2, 1.20.0rc3, 1.20.0, 1.20.1, 1.21.0rc1, 1.21.1rc1, 1.21.1, 1.22.0rc1, 1.22.0, 1.22.1, 1.23.0rc1, 1.23.0, 1.23.1, 1.24.0rc1, 1.24.0, 1.24.1, 1.24.3, 1.25.0rc1, 1.25.0, 1.26.0rc1, 1.26.0, 1.27.0rc1, 1.27.0rc2, 1.27.1, 1.27.2, 1.28.0.dev0, 1.28.0rc1, 1.28.0rc2, 1.28.0rc3, 1.28.1, 1.29.0, 1.30.0rc1, 1.30.0, 1.31.0rc1, 1.31.0rc2, 1.31.0, 1.32.0rc1, 1.32.0, 1.33.0rc1, 1.33.0rc2, 1.33.1, 1.33.2, 1.34.0rc1, 1.34.0, 1.34.1, 1.35.0rc1, 1.35.0, 1.36.0rc1, 1.36.0, 1.36.1, 1.37.0rc1, 1.37.0, 1.37.1, 1.38.0rc1, 1.38.0, 1.38.1, 1.39.0rc1, 1.39.0)       
#8 5.912 ERROR: No matching distribution found for grpcio==1.39.0
------
executor failed running [/bin/sh -c python -m pip install -r requirements.txt]: exit code: 1
```

**Comment by yosifkit** [comment]
@wanjuntham Your issue is unrelated to the OP issue here and in a known change that you need to install any dependencies when using the Alpine-based images.

> To minimize image size, it's uncommon for additional related tools (such as `git` or `bash`) to be included in Alpine-based images. Using this image as a base, add the things you need in your own Dockerfile
>
> \- [Docker Hub description](https://github.com/docker-library/docs/tree/ab390ac2267047cfc97fcd5bb37b7d7142ee4868/python#pythonversion-alpine)

**Comment by tianon** [comment]
See https://github.com/pyranges/pyrle/commit/0fa153cffca58323b65d9da4b0b12abcfd1102b7 -- this is fixed in a newer `pyrle`.
