### ISSUE TITLE
Tox/virtualenv failing in bullseye

### ISSUE THREAD

**Issue by nradulovic** [docker-library/python#645]
Hello,

After upgrading Docker image python-3.7 from buster to bullseye, tox fails to recreate Python virtual environment correctly. Python pip cannot find all of its modules when it tries to install requirements using the virtualenv.

<details>
<summary> Here is the tox log: </summary>

```console
using tox.ini: /source/tox.ini (pid 7)
using tox-3.21.4 from /usr/lib/python3/dist-packages/tox/__init__.py (pid 7)
GLOB start: packaging 
GLOB sdist-make: /source/setup.py
[13] /source$ /usr/bin/python3 setup.py sdist --formats=zip --dist-dir /source/.tox/dist >.tox/log/GLOB-0.log
running sdist
running egg_info
creating src/lcs_ble.egg-info
writing src/lcs_ble.egg-info/PKG-INFO
writing dependency_links to src/lcs_ble.egg-info/dependency_links.txt
writing entry points to src/lcs_ble.egg-info/entry_points.txt
writing requirements to src/lcs_ble.egg-info/requires.txt
writing top-level names to src/lcs_ble.egg-info/top_level.txt
writing manifest file 'src/lcs_ble.egg-info/SOURCES.txt'
reading manifest file 'src/lcs_ble.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'src/lcs_ble.egg-info/SOURCES.txt'
running check
creating lcs_ble-1.2.0
creating lcs_ble-1.2.0/src
creating lcs_ble-1.2.0/src/lcs_ble
creating lcs_ble-1.2.0/src/lcs_ble.egg-info
copying files to lcs_ble-1.2.0...
copying MANIFEST.in -> lcs_ble-1.2.0
copying README.md -> lcs_ble-1.2.0
copying VERSION -> lcs_ble-1.2.0
copying pyproject.toml -> lcs_ble-1.2.0
copying setup.py -> lcs_ble-1.2.0
copying src/lcs_ble/__init__.py -> lcs_ble-1.2.0/src/lcs_ble
copying src/lcs_ble/__main__.py -> lcs_ble-1.2.0/src/lcs_ble
copying src/lcs_ble/bl_advertisement.py -> lcs_ble-1.2.0/src/lcs_ble
copying src/lcs_ble/bl_app_peripheral.py -> lcs_ble-1.2.0/src/lcs_ble
copying src/lcs_ble/bl_client_jsonrpc.py -> lcs_ble-1.2.0/src/lcs_ble
copying src/lcs_ble/bl_gatt_server.py -> lcs_ble-1.2.0/src/lcs_ble
copying src/lcs_ble/bl_network.py -> lcs_ble-1.2.0/src/lcs_ble
copying src/lcs_ble/bl_pairing_agent.py -> lcs_ble-1.2.0/src/lcs_ble
copying src/lcs_ble/bl_server_http.py -> lcs_ble-1.2.0/src/lcs_ble
copying src/lcs_ble/bl_utils.py -> lcs_ble-1.2.0/src/lcs_ble
copying src/lcs_ble/bluetooth_presenter.py -> lcs_ble-1.2.0/src/lcs_ble
copying src/lcs_ble/bluetooth_view.py -> lcs_ble-1.2.0/src/lcs_ble
copying src/lcs_ble/bluetooth_view_model.py -> lcs_ble-1.2.0/src/lcs_ble
copying src/lcs_ble/jsonClient.py -> lcs_ble-1.2.0/src/lcs_ble
copying src/lcs_ble/jsonrpc20.py -> lcs_ble-1.2.0/src/lcs_ble
copying src/lcs_ble/versionist.py -> lcs_ble-1.2.0/src/lcs_ble
copying src/lcs_ble.egg-info/PKG-INFO -> lcs_ble-1.2.0/src/lcs_ble.egg-info
copying src/lcs_ble.egg-info/SOURCES.txt -> lcs_ble-1.2.0/src/lcs_ble.egg-info
copying src/lcs_ble.egg-info/dependency_links.txt -> lcs_ble-1.2.0/src/lcs_ble.egg-info
copying src/lcs_ble.egg-info/entry_points.txt -> lcs_ble-1.2.0/src/lcs_ble.egg-info
copying src/lcs_ble.egg-info/requires.txt -> lcs_ble-1.2.0/src/lcs_ble.egg-info
copying src/lcs_ble.egg-info/top_level.txt -> lcs_ble-1.2.0/src/lcs_ble.egg-info
Writing lcs_ble-1.2.0/setup.cfg
creating /source/.tox/dist
creating '/source/.tox/dist/lcs_ble-1.2.0.zip' and adding 'lcs_ble-1.2.0' to it
adding 'lcs_ble-1.2.0'
adding 'lcs_ble-1.2.0/src'
adding 'lcs_ble-1.2.0/PKG-INFO'
adding 'lcs_ble-1.2.0/setup.cfg'
adding 'lcs_ble-1.2.0/setup.py'
adding 'lcs_ble-1.2.0/MANIFEST.in'
adding 'lcs_ble-1.2.0/VERSION'
adding 'lcs_ble-1.2.0/pyproject.toml'
adding 'lcs_ble-1.2.0/README.md'
adding 'lcs_ble-1.2.0/src/lcs_ble'
adding 'lcs_ble-1.2.0/src/lcs_ble.egg-info'
adding 'lcs_ble-1.2.0/src/lcs_ble/jsonClient.py'
adding 'lcs_ble-1.2.0/src/lcs_ble/bl_client_jsonrpc.py'
adding 'lcs_ble-1.2.0/src/lcs_ble/bl_app_peripheral.py'
adding 'lcs_ble-1.2.0/src/lcs_ble/versionist.py'
adding 'lcs_ble-1.2.0/src/lcs_ble/bl_advertisement.py'
adding 'lcs_ble-1.2.0/src/lcs_ble/bl_pairing_agent.py'
adding 'lcs_ble-1.2.0/src/lcs_ble/bl_utils.py'
adding 'lcs_ble-1.2.0/src/lcs_ble/bluetooth_presenter.py'
adding 'lcs_ble-1.2.0/src/lcs_ble/bluetooth_view.py'
adding 'lcs_ble-1.2.0/src/lcs_ble/bl_server_http.py'
adding 'lcs_ble-1.2.0/src/lcs_ble/bluetooth_view_model.py'
adding 'lcs_ble-1.2.0/src/lcs_ble/bl_gatt_server.py'
adding 'lcs_ble-1.2.0/src/lcs_ble/__init__.py'
adding 'lcs_ble-1.2.0/src/lcs_ble/__main__.py'
adding 'lcs_ble-1.2.0/src/lcs_ble/bl_network.py'
adding 'lcs_ble-1.2.0/src/lcs_ble/jsonrpc20.py'
adding 'lcs_ble-1.2.0/src/lcs_ble.egg-info/requires.txt'
adding 'lcs_ble-1.2.0/src/lcs_ble.egg-info/dependency_links.txt'
adding 'lcs_ble-1.2.0/src/lcs_ble.egg-info/PKG-INFO'
adding 'lcs_ble-1.2.0/src/lcs_ble.egg-info/top_level.txt'
adding 'lcs_ble-1.2.0/src/lcs_ble.egg-info/SOURCES.txt'
adding 'lcs_ble-1.2.0/src/lcs_ble.egg-info/entry_points.txt'
removing 'lcs_ble-1.2.0' (and everything under it)

GLOB finish: packaging  after 0.14 seconds
copying new sdistfile to '/root/.tox/distshare/lcs_ble-1.2.0.zip'
package .tmp/package/1/lcs_ble-1.2.0.zip links to dist/lcs_ble-1.2.0.zip (/source/.tox)
python3.7 (/usr/local/bin/python3.7) is {'executable': '/usr/local/bin/python3.7', 'implementation': 'CPython', 'version_info': [3, 7, 11, 'final', 0], 'version': '3.7.11 (default, Aug 17 2021, 16:15:07) \n[GCC 10.2.1 20210110]', 'is_64': True, 'sysplatform': 'linux', 'extra_version_info': None}
py37 uses /usr/local/bin/python3.7
py37 start: getenv /source/.tox/py37
py37 cannot reuse: -r flag
py37 create: /source/.tox/py37
setting PATH=/source/.tox/py37/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[15] /source/.tox$ /usr/bin/python3 -m virtualenv --no-download --python /usr/local/bin/python3.7 py37
created virtual environment CPython3.7.11.final.0-64 in 230ms
  creator CPython3Posix(dest=/source/.tox/py37, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/root/.local/share/virtualenv)
    added seed packages: pip==20.3.4, pkg_resources==0.0.0, setuptools==44.1.1, wheel==0.34.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
py37 installdeps: -rrequirements/development.txt, -rrequirements/testing.txt
setting PATH=/source/.tox/py37/bin:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
[24] /source$ /source/.tox/py37/bin/pip install --no-cache-dir -rrequirements/development.txt -rrequirements/testing.txt
Traceback (most recent call last):
  File "/source/.tox/py37/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
  File "/source/.tox/py37/lib/python3.7/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/source/.tox/py37/lib/python3.7/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/source/.tox/py37/lib/python3.7/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/source/.tox/py37/lib/python3.7/site-packages/pip/_internal/cli/cmdoptions.py", line 23, in <module>
    from pip._vendor.packaging.utils import canonicalize_name
ModuleNotFoundError: No module named 'pip._vendor.packaging'
ERROR: invocation failed (exit code 1)
ERROR: could not install deps [-rrequirements/development.txt, -rrequirements/testing.txt]; v = InvocationError('/source/.tox/py37/bin/pip install --no-cache-dir -rrequirements/development.txt -rrequirements/testing.txt', 1)
py37 finish: getenv /source/.tox/py37 after 0.51 seconds
___________________________________ summary ____________________________________
ERROR:   py37: could not install deps [-rrequirements/development.txt, -rrequirements/testing.txt]; v = InvocationError('/source/.tox/py37/bin/pip install --no-cache-dir -rrequirements/development.txt -rrequirements/testing.txt', 1)
cleanup /source/.tox/.tmp/package/1/lcs_ble-1.2.0.zip
```

</details>

The tox.ini file:
```ini
[tox]
envlist =
    docs
    lint
    py{37,38}
# Define the minimal tox version required to run;
# if the host tox is less than this the tool with create an environment and
# provision it with a tox that satisfies it under provision_tox_env.
# At least this version is needed for PEP 517/518 support.
minversion = 3.3.0
# Activate isolated build environment. tox will use a virtual environment
# to build a source distribution from the source tree. For build tools and
# arguments use the pyproject.toml file as specified in PEP-517 and PEP-518.
isolated_build = true

# When creating package prevent inheriting dependencies from testenv
[testenv:.package]
# No additional dependencies besides PEP 517 (specified in pyproject.toml)
deps =

# This environment is used to execute unit-tests
[testenv]
description =
    Executing unit-tests.
# Pip sometimes fails to install correctly packages when using cached information
install_command =
    pip install --no-cache-dir {opts} {packages}
deps = 
    -r requirements/development.txt
    -r requirements/testing.txt
commands =
    python -m unittest tests/unittests/test...py

# This environment is used to build documentation
[testenv:docs]
description =
    Generate and build Python source documentation to various document formats.
whitelist_externals = make
# Pip sometimes fails to install correctly packages when using cached information
install_command =
    pip install --no-cache-dir {opts} {packages}
deps =
    -r requirements/development.txt
    Sphinx
commands =
    make -C docs/btif html
    make -C docs/btif latexpdf

# This environment is used to lint the project
[testenv:lint]
description =
    Linting syntactical and stylistic problems in Python source code.
# Pip sometimes fails to install correctly vext packages when using cached
# information
install_command =
    pip install --no-cache-dir {opts} {packages}
deps = 
    -r requirements/development.txt
    -r requirements/testing.txt
    pylint
commands =
    pylint src/.../a_lot_of_files_here
```
When I execute the failing command directly in Docker, it will succed.

May I get additional pointers where and how to look for the problem? Thanks

**Comment by tianon** [comment]
Invoking `/usr/bin/python3` inside the `python:*` images is almost always going to be a mistake -- you want `/usr/local/bin/python` instead.
