### ISSUE TITLE
CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by cyberb** [docker-library/python#650]
Hello,

I am getting ssl verify failed errors on various python docker images, could you help?
Here is the command:

```
sudo docker run -it  python:3.9-slim-bullseye bash -c "pip install requests==2.11.1 && python -c 'import requests; requests.get(\"https://valid-isrgrootx1.letsencrypt.org\")'"
```

Output

```
Unable to find image 'python:3.9-slim-bullseye' locally
3.9-slim-bullseye: Pulling from library/python
bd897bb914af: Pull complete 
ceddbac0d90d: Pull complete 
5079d073ba60: Pull complete 
5be4ca178df0: Pull complete 
92b646d03eaf: Pull complete 
Digest: sha256:8434c99df85cc274108beac4465d4abbc4459956bb2b7a84073636ac5f4b7c1a
Status: Downloaded newer image for python:3.9-slim-bullseye
Collecting requests==2.11.1
  Downloading requests-2.11.1-py2.py3-none-any.whl (514 kB)
     |████████████████████████████████| 514 kB 3.2 MB/s 
Installing collected packages: requests
Successfully installed requests-2.11.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/packages/urllib3/connectionpool.py", line 592, in urlopen
    httplib_response = self._make_request(conn, method, url,
  File "/usr/local/lib/python3.9/site-packages/requests/packages/urllib3/connectionpool.py", line 352, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.9/site-packages/requests/packages/urllib3/connectionpool.py", line 831, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.9/site-packages/requests/packages/urllib3/connection.py", line 284, in connect
    self.sock = ssl_wrap_socket(conn, self.key_file, self.cert_file,
  File "/usr/local/lib/python3.9/site-packages/requests/packages/urllib3/util/ssl_.py", line 308, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 413, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.9/site-packages/requests/packages/urllib3/connectionpool.py", line 621, in urlopen
    raise SSLError(e)
requests.packages.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)
```

The commands I have tried with the same error:
```
sudo docker run -it  python:3.9.7-bullseye bash -c "pip install requests==2.11.1 && python -c 'import requests; requests.get(\"https://valid-isrgrootx1.letsencrypt.org\")'"

sudo docker run -it  python:3.9.7-slim-bullseye bash -c "pip install requests==2.11.1 && python -c 'import requests; requests.get(\"https://valid-isrgrootx1.letsencrypt.org\")'"

sudo docker run -it  python:3.9-slim-bullseye bash -c "pip install requests==2.11.1 && python -c 'import requests; requests.get(\"https://valid-isrgrootx1.letsencrypt.org\")'"

sudo docker run -it  python:3.9-slim-buster bash -c "pip install requests==2.11.1 && python -c 'import requests; requests.get(\"https://valid-isrgrootx1.letsencrypt.org\")'"
```

**Comment by cyberb** [comment]
It is probably related to this: https://community.letsencrypt.org/t/help-thread-for-dst-root-ca-x3-expiration-september-2021/149190
but I am not sure how to fix it. `google.com` is fine for example.

**Comment by cyberb** [comment]
workaround: 
```
export REQUESTS_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt
```

**Comment by cyberb** [comment]
actually latest `requests==2.26.0` has no issues
