### ISSUE TITLE
pip goes broken after executed once

### ISSUE THREAD

**Issue by butflame** [docker-library/python#713]
HI, I've meet some thing confusing.
My OS: `Linux xxx 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
Docker version: `Docker version 19.03.12, build 48a66213fe`

Here's a simplified Dockerfile:
```Dockerfile
FROM python:3.9.2
RUN pip -V
RUN pip -V
```
As you see I just run `pip -V` twice, but the second time failed when building, as output blow:
```
Sending build context to Docker daemon  3.072kB
Step 1/3 : FROM python:3.9.2
 ---> 587b1bc803b3
Step 2/3 : RUN pip -V
 ---> Running in 615a91246707
pip 21.0.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
Removing intermediate container 615a91246707
 ---> bd03269b2b98
Step 3/3 : RUN pip -V
 ---> Running in 9299dd7727b9
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip._internal.cli.main'
The command '/bin/sh -c pip -V' returned a non-zero code: 1
```
---
Then I tried more to figure out——check the module:
```Dockerfile
FROM python:3.9.2
RUN ls -l /usr/local/lib/python3.9/site-packages/pip/_internal/cli
RUN pip -V
RUN ls -l /usr/local/lib/python3.9/site-packages/pip/_internal/cli
RUN pip -V
```
It seems the directory was truncated by the first call:
```
Sending build context to Docker daemon  3.072kB
Step 1/5 : FROM python:3.9.2
 ---> 587b1bc803b3
Step 2/5 : RUN ls -l /usr/local/lib/python3.9/site-packages/pip/_internal/cli
 ---> Running in 21114b59ecef
total 124
-rw-r--r-- 1 root root   136 Mar 31  2021 __init__.py
drwxr-xr-x 2 root root  4096 Mar 31  2021 __pycache__
-rw-r--r-- 1 root root  6711 Mar 31  2021 autocompletion.py
-rw-r--r-- 1 root root  8127 Mar 31  2021 base_command.py
-rw-r--r-- 1 root root 29547 Mar 31  2021 cmdoptions.py
-rw-r--r-- 1 root root   978 Mar 31  2021 command_context.py
-rw-r--r-- 1 root root  2641 Mar 31  2021 main.py
-rw-r--r-- 1 root root  2894 Mar 31  2021 main_parser.py
-rw-r--r-- 1 root root 10404 Mar 31  2021 parser.py
-rw-r--r-- 1 root root  9083 Mar 31  2021 progress_bars.py
-rw-r--r-- 1 root root 16470 Mar 31  2021 req_command.py
-rw-r--r-- 1 root root  5614 Mar 31  2021 spinners.py
-rw-r--r-- 1 root root   122 Mar 31  2021 status_codes.py
Removing intermediate container 21114b59ecef
 ---> 576b8657143f
Step 3/5 : RUN pip -V
 ---> Running in 67e738c4c85d
pip 21.0.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
Removing intermediate container 67e738c4c85d
 ---> c4839cd9e25c
Step 4/5 : RUN ls -l /usr/local/lib/python3.9/site-packages/pip/_internal/cli
 ---> Running in 091cb210b63c
total 4
drwxr-xr-x 1 root root 4096 Apr  3 19:05 __pycache__
Removing intermediate container 091cb210b63c
 ---> f7fa9134164d
Step 5/5 : RUN pip -V
 ---> Running in c495d95680fa
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
ModuleNotFoundError: No module named 'pip._internal.cli.main'
The command '/bin/sh -c pip -V' returned a non-zero code: 1
```
---
I tried other versions like python:3.9.0 and python:3.9.1, It's all good.
But some different error occured with latest python:3.9.12:
```
Sending build context to Docker daemon  3.072kB
Step 1/3 : FROM python:3.9.12
 ---> 782717491ec4
Step 2/3 : RUN pip -V
 ---> Running in 051cf6e2f062
pip 22.0.4 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
Removing intermediate container 051cf6e2f062
 ---> 8c4f19f36f9d
Step 3/3 : RUN pip -V
 ---> Running in 7bee2bbcf432
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = '/usr/local/bin/python'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = '/usr/local/bin/python'
  sys.base_prefix = '/usr/local'
  sys.base_exec_prefix = '/usr/local'
  sys.platlibdir = 'lib'
  sys.executable = '/usr/local/bin/python'
  sys.prefix = '/usr/local'
  sys.exec_prefix = '/usr/local'
  sys.path = [
    '/usr/local/lib/python39.zip',
    '/usr/local/lib/python3.9',
    '/usr/local/lib/python3.9/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
LookupError: no codec search functions registered: can't find encoding

Current thread 0x00007f83aa620740 (most recent call first):
<no Python frame>
The command '/bin/sh -c pip -V' returned a non-zero code: 1
```
---
As for the error with 3.9.2, It seems to be resolved by upgrade pip first:
```Dockerfile
FROM python:3.9.2
RUN pip install --upgrade pip
RUN pip -V
RUN pip -V
```
But I'm not sure is this the right way.

---

** Btw: Still have no idea about the error with 3.9.12 **

**Comment by butflame** [comment]
<img width="1438" alt="WechatIMG115" src="https://user-images.githubusercontent.com/24364710/161509764-ffa4de57-f3e2-44d9-a418-37bf5f2f09b6.png">
I've checked the layers with `dive`, it looks like the `pip -V` command removed tons of files and added tons of `__pycache__`

**Comment by wglambert** [comment]
I'm not able to reproduce

<details>
<summary> docker build test 1 </summary>

```console
$ docker build -t python:test - << EOF
FROM python:3.9.2
RUN pip -V
RUN pip -V
EOF

Sending build context to Docker daemon  2.048kB
Step 1/3 : FROM python:3.9.2
 ---> 587b1bc803b3
Step 2/3 : RUN pip -V
 ---> Running in e7bef78ebf83
pip 21.0.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
Removing intermediate container e7bef78ebf83
 ---> 0fbf0f8d3fbb
Step 3/3 : RUN pip -V
 ---> Running in d2b922785bf3
pip 21.0.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
Removing intermediate container d2b922785bf3
 ---> 76e26f7f9bff
Successfully built 76e26f7f9bff
Successfully tagged python:test
```

</details>

<details>
<summary> docker build test 2 </summary>

```console
$ docker build -t python:test - << EOF
FROM python:3.9.2
RUN ls -l /usr/local/lib/python3.9/site-packages/pip/_internal/cli
RUN pip -V
RUN ls -l /usr/local/lib/python3.9/site-packages/pip/_internal/cli
RUN pip -V
EOF

Sending build context to Docker daemon  2.048kB
Step 1/5 : FROM python:3.9.2
 ---> 587b1bc803b3
Step 2/5 : RUN ls -l /usr/local/lib/python3.9/site-packages/pip/_internal/cli
 ---> Running in c055ce16e1e3
total 124
-rw-r--r-- 1 root root   136 Mar 31  2021 __init__.py
drwxr-xr-x 2 root root  4096 Mar 31  2021 __pycache__
-rw-r--r-- 1 root root  6711 Mar 31  2021 autocompletion.py
-rw-r--r-- 1 root root  8127 Mar 31  2021 base_command.py
-rw-r--r-- 1 root root 29547 Mar 31  2021 cmdoptions.py
-rw-r--r-- 1 root root   978 Mar 31  2021 command_context.py
-rw-r--r-- 1 root root  2641 Mar 31  2021 main.py
-rw-r--r-- 1 root root  2894 Mar 31  2021 main_parser.py
-rw-r--r-- 1 root root 10404 Mar 31  2021 parser.py
-rw-r--r-- 1 root root  9083 Mar 31  2021 progress_bars.py
-rw-r--r-- 1 root root 16470 Mar 31  2021 req_command.py
-rw-r--r-- 1 root root  5614 Mar 31  2021 spinners.py
-rw-r--r-- 1 root root   122 Mar 31  2021 status_codes.py
Removing intermediate container c055ce16e1e3
 ---> ebe8d7de4887
Step 3/5 : RUN pip -V
 ---> Running in 254e6c131863
pip 21.0.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
Removing intermediate container 254e6c131863
 ---> 25303bf57b6f
Step 4/5 : RUN ls -l /usr/local/lib/python3.9/site-packages/pip/_internal/cli
 ---> Running in c150be88b05a
total 124
-rw-r--r-- 1 root root   136 Mar 31  2021 __init__.py
drwxr-xr-x 1 root root  4096 Apr  4 21:18 __pycache__
-rw-r--r-- 1 root root  6711 Mar 31  2021 autocompletion.py
-rw-r--r-- 1 root root  8127 Mar 31  2021 base_command.py
-rw-r--r-- 1 root root 29547 Mar 31  2021 cmdoptions.py
-rw-r--r-- 1 root root   978 Mar 31  2021 command_context.py
-rw-r--r-- 1 root root  2641 Mar 31  2021 main.py
-rw-r--r-- 1 root root  2894 Mar 31  2021 main_parser.py
-rw-r--r-- 1 root root 10404 Mar 31  2021 parser.py
-rw-r--r-- 1 root root  9083 Mar 31  2021 progress_bars.py
-rw-r--r-- 1 root root 16470 Mar 31  2021 req_command.py
-rw-r--r-- 1 root root  5614 Mar 31  2021 spinners.py
-rw-r--r-- 1 root root   122 Mar 31  2021 status_codes.py
Removing intermediate container c150be88b05a
 ---> 20a32da9b783
Step 5/5 : RUN pip -V
 ---> Running in 6494370f87a2
pip 21.0.1 from /usr/local/lib/python3.9/site-packages/pip (python 3.9)
Removing intermediate container 6494370f87a2
 ---> eb333c630aa9
Successfully built eb333c630aa9
Successfully tagged python:test
```

</details>

I also tested it on [labs.play-with-docker.com](https://labs.play-with-docker.com)
![image](https://user-images.githubusercontent.com/26428991/161634970-4fc8f0fd-5d8f-4dd3-a402-0e112b7f339b.png)


It seems like something with the host's environment, maybe resource or hardware related

**Comment by butflame** [comment]
thx,
I tried on another host with kernel `3.10.0-1160.25.1.el7.x86_64`, all things good.
Seems it may occured with some certain host with legacy kernel version.
