### ISSUE TITLE
'subprocess.check_call' can't work on alpine based images

### ISSUE THREAD

**Issue by Metaphorme** [docker-library/python#775]
Dear Developers:

Thank you for you to read this! It seems that `subprocess.check_call` can't work as planned on alpine based images. Please allow me to write a simple python script to describe this.

On **Alpine** based images: (e.g., tag:3.11.0-alpine3.16)

```bash
FROM python:3.11.0-alpine3.16

RUN set -x \
    && echo -e '#!/bin/bash\necho Working!' > test.sh \
    && chmod +x test.sh \
    && echo -e 'import subprocess\nsubprocess.check_call(["./test.sh"])' > test.py \
    && cat test.sh \
    && cat test.py \
    && python3 test.py
```

I got error building log as followed:
```bash
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM python:3.11.0-alpine3.16
 ---> 91c0c14478fa
Step 2/2 : RUN set -x     && echo -e '#!/bin/bash\necho Working!' > test.sh     && chmod +x test.sh     && echo -e 'import subprocess\nsubprocess.check_call(["./test.sh"])' > test.py     && cat test.sh     && cat test.py     && python3 test.py
 ---> Running in 1c267a11a4e8
+ echo -e '#!/bin/bash\necho Working!'
+ chmod +x test.sh
+ echo -e 'import subprocess\nsubprocess.check_call(["./test.sh"])'
+ cat test.sh
#!/bin/bash
echo Working!
+ cat test.py
import subprocess
subprocess.check_call(["./test.sh"])
+ python3 test.py
Traceback (most recent call last):
  File "//test.py", line 2, in <module>
    subprocess.check_call(["./test.sh"])
  File "/usr/local/lib/python3.11/subprocess.py", line 408, in check_call
    retcode = call(*popenargs, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 389, in call
    with Popen(*popenargs, **kwargs) as p:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 1022, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.11/subprocess.py", line 1899, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './test.sh'
The command '/bin/sh -c set -x     && echo -e '#!/bin/bash\necho Working!' > test.sh     && chmod +x test.sh     && echo -e 'import subprocess\nsubprocess.check_call(["./test.sh"])' > test.py     && cat test.sh     && cat test.py     && python3 test.py' returned a non-zero code: 1
```
It cannot work on other alpine based images.
But it's works well on **other images**(e.g., tag:3.11.0-buster)

```bash
FROM python:3.11.0-buster

RUN set -x \
    && echo '#!/bin/bash\necho Working!' > test.sh \
    && chmod +x test.sh \
    && echo 'import subprocess\nsubprocess.check_call(["./test.sh"])' > test.py \
    && cat test.sh \
    && cat test.py \
    && python3 test.py
```

I got building log as followed:

```bash
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM python:3.11.0-buster
3.11.0-buster: Pulling from library/python
2730d739afad: Already exists 
a122751b3533: Already exists 
0a277c3efe7c: Already exists 
25c35b81c503: Already exists 
cb8cde86ddb2: Already exists 
3921145f3c18: Already exists 
9c97ce82cb73: Already exists 
fa2fe39630c0: Already exists 
df87241a7677: Already exists 
Digest: sha256:b6baf17766d69c7b11a2c1d4ce2121401a91e93a2e2e8f96fd43451a6eea72b6
Status: Downloaded newer image for python:3.11.0-buster
 ---> 5a80b38989b8
Step 2/2 : RUN set -x     && echo '#!/bin/bash\necho Working!' > test.sh     && chmod +x test.sh     && echo 'import subprocess\nsubprocess.check_call(["./test.sh"])' > test.py     && cat test.sh     && cat test.py     && python3 test.py
 ---> Running in f6f95adcc204
+ echo #!/bin/bash\necho Working!
+ chmod +x test.sh
+ echo import subprocess\nsubprocess.check_call(["./test.sh"])
+ cat test.sh
#!/bin/bash
echo Working!
+ cat test.py
import subprocess
subprocess.check_call(["./test.sh"])
+ python3 test.py
Working!
Removing intermediate container f6f95adcc204
 ---> acce1c91a393
Successfully built acce1c91a393
```
  
I will be very appreciated if we could work together to fix this. 
Thanks!

**Comment by Metaphorme** [comment]
Sorry, alpine use ash as shell.
Try this to fix it:
```bash
FROM python:3.11.0-alpine3.16

RUN set -x \
    && echo -e '#!/bin/ash\necho Working!' > test.sh \
    && chmod +x test.sh \
    && echo -e 'import subprocess\nsubprocess.check_call(["./test.sh"])' > test.py \
    && cat test.sh \
    && cat test.py \
    && python3 test.py
```
