### ISSUE TITLE
Unable to install scipy in the python:3 image

### ISSUE THREAD

**Issue by braunmagrin** [docker-library/python#88]
I'm trying to install some libraries on top of the python:3 image but it isn't working due to some missing libraries, e.g. openblas, mkl, vml, guide, lapack.

Maybe they have been removed during the purge. Any ideas on how to solve it other than reinstalling them by hand?

Here's the terminal output:

```
$ docker run -it python:3 bash
Unable to find image 'python:3' locally
3: Pulling from library/python

Digest: sha256:d4e91d39a14154f5d5cb33048e3a8f03d3316e1acf585383519bd89a0611d3d7
Status: Downloaded newer image for python:3
root@3b9e3eb5d1d6:/# pip install scipy
Collecting scipy
  Downloading scipy-0.17.0.tar.gz (12.4MB)
    100% |████████████████████████████████| 12.4MB 37kB/s 
Collecting numpy>=1.6.2 (from scipy)
  Downloading numpy-1.10.4.tar.gz (4.1MB)
    100% |████████████████████████████████| 4.1MB 118kB/s 
Installing collected packages: numpy, scipy
  Running setup.py install for numpy
  Running setup.py install for scipy
    Complete output from command /usr/local/bin/python3.5 -c "import setuptools, tokenize;__file__='/tmp/pip-build-e9cx2_9t/scipy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-gxr2_g9y-record/install-record.txt --single-version-externally-managed --compile:
    lapack_opt_info:
    openblas_lapack_info:
      libraries openblas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE

    lapack_mkl_info:
    mkl_info:
      libraries mkl,vml,guide not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE

      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas,tatlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries tatlas,tatlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib
      libraries tatlas,tatlas not found in /usr/lib/x86_64-linux-gnu
      libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
      libraries satlas,satlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries satlas,satlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib
      libraries satlas,satlas not found in /usr/lib/x86_64-linux-gnu
      libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib
      libraries ptf77blas,ptcblas,atlas not found in /usr/lib/x86_64-linux-gnu
      libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
      libraries f77blas,cblas,atlas not found in /usr/local/lib
      libraries lapack_atlas not found in /usr/local/lib
      libraries f77blas,cblas,atlas not found in /usr/lib
      libraries lapack_atlas not found in /usr/lib
      libraries f77blas,cblas,atlas not found in /usr/lib/x86_64-linux-gnu
      libraries lapack_atlas not found in /usr/lib/x86_64-linux-gnu
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    lapack_info:
      libraries lapack not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/x86_64-linux-gnu']
      NOT AVAILABLE

    lapack_src_info:
      NOT AVAILABLE

      NOT AVAILABLE

    /usr/local/lib/python3.5/site-packages/numpy/distutils/system_info.py:1552: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      warnings.warn(AtlasNotFoundError.__doc__)
    /usr/local/lib/python3.5/site-packages/numpy/distutils/system_info.py:1563: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      warnings.warn(LapackNotFoundError.__doc__)
    /usr/local/lib/python3.5/site-packages/numpy/distutils/system_info.py:1566: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      warnings.warn(LapackSrcNotFoundError.__doc__)
    Running from scipy source directory.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-e9cx2_9t/scipy/setup.py", line 265, in <module>
        setup_package()
      File "/tmp/pip-build-e9cx2_9t/scipy/setup.py", line 262, in setup_package
        setup(**metadata)
      File "/usr/local/lib/python3.5/site-packages/numpy/distutils/core.py", line 135, in setup
        config = configuration()
      File "/tmp/pip-build-e9cx2_9t/scipy/setup.py", line 182, in configuration
        config.add_subpackage('scipy')
      File "/usr/local/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 1002, in add_subpackage
        caller_level = 2)
      File "/usr/local/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 971, in get_subpackage
        caller_level = caller_level + 1)
      File "/usr/local/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 908, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy/setup.py", line 15, in configuration
        config.add_subpackage('linalg')
      File "/usr/local/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 1002, in add_subpackage
        caller_level = 2)
      File "/usr/local/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 971, in get_subpackage
        caller_level = caller_level + 1)
      File "/usr/local/lib/python3.5/site-packages/numpy/distutils/misc_util.py", line 908, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy/linalg/setup.py", line 20, in configuration
        raise NotFoundError('no lapack/blas resources found')
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found
```

**Comment by ZelphirKaltstahl** [comment]
Have the same issue here, although *all* of those are installed on my system or in the virtualenv I am using. Somehow it doesn't find the libraries.

**Comment by hamdigdoura** [comment]
I have the same issue with virtualenvwrapper.

**Comment by ZelphirKaltstahl** [comment]
Turns out it all worked when I created a new virutalenv. The other one was created by anaconda and that's why the dependencies couldn't be found by pip.

**Comment by pcorpet** [comment]
I managed to do the install by preinstalling some debian packages before:
RUN apt-get update -qqy && apt-get install -qqy libopenblas-dev gfortran

**Comment by tianon** [comment]
I think this is fixed now! :smile:
```console
$ docker run -it --rm python:3 bash
root@a31adf41234d:/# pip install scipy
Collecting scipy
  Downloading scipy-0.18.0-cp35-cp35m-manylinux1_x86_64.whl (42.0MB)
    100% |████████████████████████████████| 42.0MB 58kB/s 
Installing collected packages: scipy
Successfully installed scipy-0.18.0
root@a31adf41234d:/# 
```

**Comment by CK05** [comment]
I found a local, portable install was helpful for tricky situations, winpython for example. You keep all the packages in there as well and can just travel with your full Python install. I had good luck with enthought, but when a tricky issue came up, winpython was the answer.

**Comment by braunmagrin** [comment]
I've retested it and it's working now. Great! Not sure how it was fixed, though.
