### ISSUE TITLE
Alpine 3.3, Python 2.7.11, urllib2 SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by danielfaust** [docker-library/python#92]
```
FROM python:2-alpine
CMD ["python", "-c", "import urllib2; response = urllib2.urlopen('https://www.python.org')"]
```
is causing 
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/local/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/local/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/usr/local/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>
```

Is this normal?

**Comment by danielfaust** [comment]
I didn't `apk add ca-certificates` to the final image, so there's that.

**Comment by giuliobraini** [comment]
It worked for me also!

`RUN apk --no-cache add ca-certificates`
