### ISSUE TITLE
i386/python doesn't contain Rust

### ISSUE THREAD

**Issue by BinarSkugga** [docker-library/python#986]
As opposed to the traditional Docker image for Python, the i386 version doesn't seem to have rust installed. Rust can be built using i686, I have managed to make it working by lifting the Rust docker image script:

```Dockerfile
# Build Rust
ENV RUSTUP_HOME=/usr/local/rustup \
    CARGO_HOME=/usr/local/cargo \
    PATH=/usr/local/cargo/bin:$PATH \
    RUST_VERSION=1.82.0

RUN set -eux; \
    rustArch='i686-unknown-linux-gnu'; rustupSha256='0a6bed6e9f21192a51f83977716466895706059afb880500ff1d0e751ada5237'; \
    url="https://static.rust-lang.org/rustup/archive/1.27.1/${rustArch}/rustup-init"; \
    wget "$url"; \
    echo "${rustupSha256} *rustup-init" | sha256sum -c -; \
    chmod +x rustup-init; \
    ./rustup-init -y --no-modify-path --profile minimal --default-toolchain $RUST_VERSION --default-host ${rustArch}; \
    rm rustup-init; \
    chmod -R a+w $RUSTUP_HOME $CARGO_HOME; \
    rustup --version; \
    cargo --version; \
    rustc --version;
```

**Comment by tianon** [comment]
I'm confused -- none of the Python images (should) have Rust installed in them? :thinking:

**Comment by BinarSkugga** [comment]
That's what I thought too. Maybe it's glibc ? I use the bullseye version but inside my pipeline I basically build 2 images, one with python:3.12.7-bullsyeye and one i386/python:3.12.7-bullsyeye. In the pipeline I require to install `orjson` in python which requires Rust: https://github.com/ijl/orjson/blob/master/CHANGELOG.md#changed-1

Build for the normal python image works fine but in i386 i get this error:
```
Collecting orjson==3.10.7 (from sollum-galactus==4.21-dev17)
  Downloading orjson-3.10.7.tar.gz (5.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 64.5 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      
      Cargo, the Rust package manager, is not installed or is not on PATH.
      This package requires Rust and Cargo to compile extensions. Install it through
      the system's package manager or via https://rustup.rs/
      
      Checking for Rust toolchain....
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
Traceback (most recent call last):
  File "/builds/sollum/sollummicroservicearchitecture/smclientportal/setup.py", line 99, in <module>
    gitlab_install(personal_access_token, *requirements)
  File "/builds/sollum/sollummicroservicearchitecture/smclientportal/setup.py", line 79, in gitlab_install
    raise RuntimeError("Could not install successfully")
RuntimeError: Could not install successfully
```

**Comment by BinarSkugga** [comment]
Here's a minimal reproduction:
![image](https://github.com/user-attachments/assets/34511a98-8a5b-40e8-b3c9-d311417fad10)
![image](https://github.com/user-attachments/assets/e9ae4a26-622c-47bd-9ed6-365f118f978b)

**Comment by edmorley** [comment]
I suspect the difference is that when using the x86_64 image the build is actually using the precompiled `orjson` wheel, so doesn't need Rust installed, whereas for the i386 image there isn't a compatible wheel:
https://pypi.org/project/orjson/#files

**Comment by BinarSkugga** [comment]
That would actually make a lot of sense. Thanks for the help !
